import { useState, useEffect } from 'react';
import { Button, OtpInput, ErrorMessage } from '../../components/ui';
import { ShieldCheck, Lock, Clock } from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import { supabase } from '../../lib/supabase';

export default function MfaVerify() {
  const { user, verifyMfa } = useAuth();

  const [code, setCode] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [isLockedOut, setIsLockedOut] = useState(false);
  const [secondsRemaining, setSecondsRemaining] = useState<number>(0);

  // Check lockout on initial mount
  useEffect(() => {
    async function checkLockout() {
      if (!user) return;
      try {
        const { data: isLocked } = await supabase.rpc('check_mfa_lockout', {
          p_user_id: user.id,
        });
        if (isLocked) {
          setIsLockedOut(true);
          setSecondsRemaining(300); // 5 min countdown
        }
      } catch {
        // Ignored
      }
    }
    checkLockout();
  }, [user]);

  // Countdown timer when locked out
  useEffect(() => {
    if (!isLockedOut || secondsRemaining <= 0) return;

    const interval = setInterval(() => {
      setSecondsRemaining((prev) => {
        if (prev <= 1) {
          setIsLockedOut(false);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(interval);
  }, [isLockedOut, secondsRemaining]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isLockedOut) return;

    if (code.length !== 6) {
      setError('Please enter the 6-digit code from your authenticator app.');
      return;
    }

    setLoading(true);
    setError(null);

    const res = await verifyMfa(code);

    if (!res.success) {
      if (res.isLocked) {
        setIsLockedOut(true);
        setSecondsRemaining(300);
        setError(null);
      } else if (res.attemptsRemaining !== undefined) {
        setError(`Invalid authentication code. ${res.attemptsRemaining} attempt(s) remaining before temporary lockout.`);
      } else {
        setError(res.error || 'Invalid code. Please try again.');
      }
      setLoading(false);
    }
  };

  return (
    <div className="w-full rounded-card border border-border bg-white p-7 sm:p-9 shadow-xs">
      {isLockedOut ? (
        // Calm lockout state: lock icon, countdown timer, no code input visible
        <div className="text-center py-4 space-y-4">
          <div className="inline-flex h-16 w-16 rounded-2xl bg-clay/10 border border-clay/30 p-2 items-center justify-center shadow-2xs text-clay mx-auto">
            <Lock className="w-8 h-8 text-clay" />
          </div>

          <h2 className="font-heading text-xl font-bold text-navy tracking-tight">
            Account Temporarily Locked
          </h2>

          <p className="text-xs text-ink/80 leading-relaxed max-w-sm mx-auto font-body">
            Too many consecutive incorrect verification attempts. For your security, authentication has been temporarily paused.
          </p>

          <div className="p-4 rounded-2xl bg-cream border border-border/80 inline-flex items-center gap-2.5 text-navy font-mono font-bold text-sm">
            <Clock className="w-4 h-4 text-clay" />
            <span>
              Retries resume in {Math.floor(secondsRemaining / 60)}:
              {(secondsRemaining % 60).toString().padStart(2, '0')}
            </span>
          </div>

          <p className="text-[11px] text-gray pt-2">
            Please wait until the countdown ends, or contact your Admin for identity verification.
          </p>
        </div>
      ) : (
        <>
          <div className="text-center mb-6">
            <div className="inline-flex h-14 w-14 rounded-2xl bg-teal/15 border border-teal/40 p-2 items-center justify-center shadow-2xs mb-3 text-teal">
              <ShieldCheck className="w-7 h-7 text-teal" />
            </div>
            <h1 className="font-heading text-2xl font-bold text-navy tracking-tight">
              Two-Factor Authentication
            </h1>
            <p className="text-xs text-gray mt-2 leading-relaxed max-w-sm mx-auto font-body">
              Enter the 6-digit security code generated by your authenticator app to complete sign-in.
            </p>
          </div>

          {error && (
            <div className="mb-5">
              <ErrorMessage message={error} />
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label className="block text-center text-xs font-bold text-gray uppercase tracking-widest mb-3">
                Security Code
              </label>
              <OtpInput
                value={code}
                onChange={(val) => {
                  setCode(val);
                  if (error) setError(null);
                }}
                error={!!error}
              />
            </div>

            <Button
              type="submit"
              variant="primary"
              loading={loading}
              disabled={code.length !== 6}
              className="w-full"
            >
              Verify
            </Button>
          </form>
        </>
      )}
    </div>
  );
}
