import { useState, useEffect } from 'react';
import { supabase } from '../../lib/supabase';
import { Button, OtpInput, CodeDisplay, ErrorMessage, Spinner } from '../../components/ui';
import { ShieldCheck, Smartphone } from 'lucide-react';

export default function TotpSetup() {
  const [factorId, setFactorId] = useState<string | null>(null);
  const [qrCodeSvg, setQrCodeSvg] = useState<string | null>(null);
  const [secret, setSecret] = useState<string | null>(null);
  const [loadingEnroll, setLoadingEnroll] = useState(true);

  const [code, setCode] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [verifying, setVerifying] = useState(false);

  useEffect(() => {
    async function enrollFactor() {
      setLoadingEnroll(true);
      setError(null);
      try {
        const { data, error: enrollError } = await supabase.auth.mfa.enroll({
          factorType: 'totp',
          issuer: 'HACSA Foundation',
        });

        if (enrollError) {
          setError(enrollError.message);
        } else if (data) {
          setFactorId(data.id);
          // data.totp.qr_code is a ready-to-render SVG data URI
          setQrCodeSvg(data.totp?.qr_code || null);
          setSecret(data.totp?.secret || null);
        }
      } catch (err: any) {
        setError(err.message || 'Failed to initialize two-factor enrollment.');
      } finally {
        setLoadingEnroll(false);
      }
    }

    enrollFactor();
  }, []);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!factorId) {
      setError('MFA enrollment session not initialized.');
      return;
    }
    if (code.length !== 6) {
      setError('Please enter the 6-digit code generated by your authenticator app.');
      return;
    }

    setVerifying(true);
    setError(null);

    try {
      // 1. Challenge factor
      const { data: challenge, error: challengeError } = await supabase.auth.mfa.challenge({
        factorId,
      });

      if (challengeError) {
        setError(challengeError.message);
        setVerifying(false);
        return;
      }

      // 2. Verify code
      const { error: verifyError } = await supabase.auth.mfa.verify({
        factorId,
        challengeId: challenge.id,
        code: code.trim(),
      });

      if (verifyError) {
        setError(verifyError.message || 'Incorrect verification code. Please check your app.');
        setVerifying(false);
        return;
      }

      // 3. Finalize the account. This is the step that was previously
      // missing entirely — MFA succeeding alone never created the
      // staff_profiles row, so a person could complete every screen and
      // still have no role at all once they reached the dashboard. Safe
      // to call unconditionally: it's a no-op if a profile already
      // exists (the Admin's own bootstrap flow, or a Backup Admin
      // designation's forced TOTP step), and it independently re-checks
      // that the 6-digit code was genuinely verified before creating one.
      const { error: activateError } = await supabase.rpc('complete_staff_invite');
      if (activateError) {
        setError(
          activateError.message ||
            'Two-factor setup succeeded, but your account could not be activated. Contact your Admin.'
        );
        setVerifying(false);
        return;
      }

      // 4. On success, session is now at AAL2. Do a full page reload so route guards re-read AAL2 cleanly.
      window.location.href = '/dashboard';
    } catch (err: any) {
      setError(err.message || 'An unexpected error occurred during verification.');
      setVerifying(false);
    }
  };

  return (
    <div className="w-full rounded-card border border-border bg-white p-6 sm:p-8 shadow-xs">
      <div className="text-center mb-6">
        <div className="inline-flex h-14 w-14 rounded-2xl bg-teal/15 border border-teal/40 p-2 items-center justify-center shadow-2xs mb-3 text-teal">
          <ShieldCheck className="w-7 h-7 text-teal" />
        </div>
        <h1 className="font-heading text-xl sm:text-2xl font-bold text-navy tracking-tight">
          Set Up Two-Factor Authentication
        </h1>
        <p className="text-xs text-gray mt-2 leading-relaxed max-w-sm mx-auto font-body">
          Scan the QR code below using <strong>any standard authenticator app</strong> on your mobile device (such as Google Authenticator, Microsoft Authenticator, 1Password, or Authy).
        </p>
      </div>

      {error && (
        <div className="mb-5">
          <ErrorMessage message={error} />
        </div>
      )}

      {loadingEnroll ? (
        <div className="py-16 flex flex-col items-center justify-center gap-3">
          <Spinner className="w-8 h-8 text-teal" />
          <p className="text-xs text-gray">Enrolling authentication factor...</p>
        </div>
      ) : (
        <>
          {/* QR Code Container using ready-to-render SVG data URI */}
          {qrCodeSvg && (
            <div className="flex flex-col items-center justify-center p-5 mb-5 rounded-2xl bg-cream border border-border/80">
              <div className="p-3 bg-white rounded-xl shadow-xs border border-border">
                <img
                  src={qrCodeSvg}
                  alt="Two-Factor Authenticator QR Code"
                  className="w-48 h-48 object-contain"
                />
              </div>
              <p className="text-[11px] text-gray mt-3 flex items-center gap-1.5 font-medium">
                <Smartphone className="w-3.5 h-3.5 text-teal" />
                <span>Scan using your mobile device's authenticator app</span>
              </p>
            </div>
          )}

          {/* Manual Entry Secret Key */}
          {secret && (
            <div className="mb-6 space-y-1.5">
              <label className="block text-xs font-semibold text-ink font-body">
                Can't scan? Enter this key manually in your app:
              </label>
              <CodeDisplay code={secret} className="text-sm py-2 px-3 tracking-normal" />
            </div>
          )}

          {/* Verification Code Form */}
          <form onSubmit={handleVerify} className="space-y-5">
            <div>
              <label className="block text-center text-xs font-bold text-gray uppercase tracking-widest mb-2.5">
                Enter 6-Digit Code from Your App
              </label>
              <OtpInput
                value={code}
                onChange={(val) => {
                  setCode(val);
                  if (error) setError(null);
                }}
                error={!!error}
              />
            </div>

            <Button
              type="submit"
              variant="primary"
              loading={verifying}
              disabled={code.length !== 6}
              className="w-full"
            >
              Verify and Continue
            </Button>
          </form>
        </>
      )}
    </div>
  );
}
